[[pages]]
path = "pages/home.py"
name = "Home"
icon = "ğŸ "
url_path = "home"


[[pages]]
path = "pages/task.py"
name = "Task"
icon =  "ğŸ“Œ"
url_path = "task"

[[pages]]
path = "pages/dataset.py"
name = "Dataset"
icon =  "ğŸ“Š"
url_path = "dataset"

[[pages]]
path = "pages/model.py"
name = "Model"
icon =  "ğŸ‘¨ğŸ»â€ğŸ’»"
url_path = "model"